controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_historique_detail_result:
    path: /historique/detail/result/{resultat}
    controller: App\Controller\HistoriqueController::detail